/********************************************************************
* ../Root/TRJigsawCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../Root/TRJigsawCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTRJigsawCint();
extern void G__cpp_setup_inheritanceTRJigsawCint();
extern void G__cpp_setup_typetableTRJigsawCint();
extern void G__cpp_setup_memvarTRJigsawCint();
extern void G__cpp_setup_globalTRJigsawCint();
extern void G__cpp_setup_memfuncTRJigsawCint();
extern void G__cpp_setup_funcTRJigsawCint();
extern void G__set_cpp_environmentTRJigsawCint();
}


#include "/var/tmp//rootcint_O2YCrL.h"
